### ISSUE TITLE
"Unknown Error" inside a red notification

### ISSUE THREAD

**Issue by sang-shelton** [EpicCash/epic-gui-wallet#105]
**Describe the bug**
I have tried building and running the wallet and also using the pre-built Appimage.
They both produce the same error. 
I have mentioned the issue in a comment [here](https://github.com/EpicCash/epic-gui-wallet/issues/27#issuecomment-2077521821)
When i enter my credentials to create a new account and press "Create new wallet", i get this "Unknown error".

---

**To Reproduce**
Run the wallet app and try creating a new wallet.

---

**Expected behavior**
The wallet should be created and i should be able to access and control it.

---

**Required data**
 - Wallet log as text or screenshot
 - Config toml file or command line 
 - OS: MX Linux (All sys info [here](https://github.com/EpicCash/epic-gui-wallet/issues/27#issuecomment-2077521821))
 - Node.js Version: v18.19.0

---

**Additional context**
Nothing

**Comment by KanoczTomas** [comment]
Hi,

Look at https://github.com/EpicCash/epic-gui-wallet/releases/tag/v5.3.0 notes about libssl, I had the same error, once installed the mentioned libssl, it started working.

It is still a bug though, a descriptive error should be raised ...

**Comment by sang-shelton** [comment]
Thanks much, i was worried that libssl1 will conflict with my current libss3 and cause problems. I tried it and it worked fine. For now.
