### ISSUE TITLE
The Wallet HTTP Receive function does not work. Not listening.

### ISSUE THREAD

**Issue by norcimo** [EpicCash/epic-gui-wallet#13]
**Describe the bug**

VITEX Withdrawl to HTTP address,
generates an error.  "Transfer address is incorrect"

Upon further investigation using canuseeme.org, the wallet is not listening, though it has been instructed to do so.

No different from the previous wallet,  PORTs open.  At this time, the wallet can not receive HTTP.

**Comment by johanneshahn** [comment]
Hi,

please make sure that you set the correct IP in the epic-wallet.toml file.
Default Location is: ~/.epic/main/epic-wallet.toml


It is set to 127.0.0.1 as default form epic-wallet
#host IP for wallet listener, change to "0.0.0.0" to receive epics
api_listen_interface = "127.0.0.1"

**Comment by norcimo** [comment]
WORKED! 
Thank you!
