### ISSUE TITLE
Request For Change "Wallet successfully recovered" Text Color

### ISSUE THREAD

**Issue by Grandiose** [EpicCash/epic-gui-wallet#15]
Request For Change "Wallet successfully recovered." from RED to GREEN text

![image](https://user-images.githubusercontent.com/8078169/161847375-3998541c-9f5a-4558-a59f-e299ddf150a2.png)

**Comment by MarcioMacedoBA** [comment]
Done! [Commit](https://github.com/EpicCash/epic-gui-wallet/commit/c81dc60016bd28386f7746bb34b39890cb0f6e67)

**Comment by Grandiose** [comment]
Nice.  Thank you amazing EPIC people of planet Earth! :)
