### ISSUE TITLE
Win 10 and MacOS shows older version 3.0.0 in log file 

### ISSUE THREAD

**Issue by Grandiose** [EpicCash/epic-gui-wallet#17]
Win 10 and MacOS shows older version 3.0.0 in log file, should be current version 3.0.1 or whatever the current version is:

![image](https://user-images.githubusercontent.com/8078169/161867961-50b5ace2-bf5f-48f5-8ddc-32a2ed1517ca.png)

![image](https://user-images.githubusercontent.com/8078169/161868062-c5df0b16-40dc-437e-affa-6fcfb1833b6d.png)

**Comment by johanneshahn** [comment]
this is the cli wallet version not the gui wallet version what you see in the log
