### ISSUE TITLE
When sending EPIC CASH to VITEX using HTTP you get an error due to an invalid date.

### ISSUE THREAD

**Issue by norcimo** [EpicCash/epic-gui-wallet#20]
See sample below form the log files transaction details.
ID | 92
Slate ID | 938ea293-9ca7-41b4-9f23-8e88448ae80e
Creation date | 2022-05-03, 01:14:07
**Confirmation date | Invalid date**
Amount credited | 0.75795012
Amount debited | 1100.75895012
Fee | 0.001
Status | cancelled
Type | send

**Comment by johanneshahn** [comment]
if transaction has no confirmation then the date is 0
