### ISSUE TITLE
Re-check balance is not working

### ISSUE THREAD

**Issue by MarcioMacedoBA** [EpicCash/epic-gui-wallet#22]
**Describe the bug**
After recovering a v2 wallet on Epic GUI wallet (v3), the method "Recheck balance" presents some errors on the screen, as shown below:

![image](https://user-images.githubusercontent.com/103434829/169550365-cd55c121-6348-4b1a-a433-9935ecebdf50.png)

**To Reproduce**
 - Start a v2 Epic server on usernet;
 - Create a v2 Epic CLI wallet on usernet;
 - Mine some coins to it;
 - Stop the v2 Epic server;
 - Start the v3 Epic GUI wallet;
 - Recover the v2 Epic CLI wallet using the Epic GUI wallet on usernet;
 - Start the v3 Epic server on usernet;
 - Login using the new account and password of the recovered Epic GUI Wallet on usernet;
 - Click on "Recheck Balance"

**Expected behavior**
The "Recheck balance" should run the "scan" command without any errors.

**Required data**
OS: Windows
Epic server: master branch
Epic wallet: the same one that comes with the Epic GUI wallet project (available in "resources/bin/win")
Epic miner: master branch
Node version: v16.15.0
npm version: 8.5.5

**Comment by johanneshahn** [comment]
The error message say it clear: Unable to contact node .... 
Check that your node is accesible by wallet.
