### ISSUE TITLE
"Wallet successfully recovered" is shown even when the node is not accessible

### ISSUE THREAD

**Issue by MarcioMacedoBA** [EpicCash/epic-gui-wallet#23]
**Describe the bug**
When a user tries to recover a wallet, and the recovery fails due to a connection error to the server, the application incorrectly prints "wallet successfully recovered".

**To Reproduce**
 - Open the Epic GUI Wallet;
 - Click on "Recover";
 - Add a valid seed phrase from usernet/floonet wallet;
 - Click on "Finish enter seed phrase";
 - Select the wallet folder;
 - Fill the empty blanks (account, and the others);
 - Select "Mainnet" (or another net that is different from the one where the seed phrase was generated);
 - Click on "Recover";
 
**Expected behavior**
The application should report that the Epic server is not running/Node is not accessible.

**Required data**
OS: Windows
Epic server: master branch
Epic wallet: the same one that comes with the Epic GUI wallet project (available in "resources/bin/win")
Epic miner: master branch
Node version: v16.15.0
npm version: 8.5.5

**Comment by johanneshahn** [comment]
You need no node to recover the wallet. If node is not accesible at this stage does not matter
