### ISSUE TITLE
Change Request: GUI v4 Dashboard

### ISSUE THREAD

**Issue by gbkelley** [EpicCash/epic-gui-wallet#33]
Last transaction showing detail by default - should only show if you click Details button. Doesn't hide/show if you click Details toggle like newer transactions in list.

Option in Setup to show either Transactions or Coins as default (I prefer to see Coins and select Transactions if I need more detail). Remember selection when returning/selecting Dashboard - always defaults to transactions.

Avatar using first two letters of friendly name - just use first letter - two looks odd

**Comment by johanneshahn** [comment]
Last Transaction in list is now closed.

feel free to open a new issue for Coins-Tap selected as default and new Issue for odd look
