### ISSUE TITLE
Internal node not syncing help needed.

### ISSUE THREAD

**Issue by Leviyf** [EpicCash/epic-gui-wallet#37]
**Describe the bug**
When I go to settings and switch to internal node it does sync and remains on 0%. Other times it works though so it is random. However, https://fastepic.eu:3413 this node works and after I switch to this node and then back to internal node the internal node sync in a instant. 

**To Reproduce**

**Expected behavior**
I expect the internal node to sync immediately right when I enter the wallet.

**Required data**
 
![20220729_193600](https://user-images.githubusercontent.com/110196709/181864314-8acf6686-a564-40db-9ca7-698ff671b0fd.png)

 - Config toml file or command line 
 - Windows 11
 - Node.js Version

**Additional context**
I do not know how to debug this. Lmk if I am missing and have not added any curcial information. I pretty much just ran into some problems and I am reporting them because I do not know how to fix them. Maybe reporting these bugs I have experienced helps.

**Comment by johanneshahn** [comment]
is there a toast message on the right bottom. "Node started"?
Then you should wait some seconds before you receive the status from the node.

**Comment by Leviyf** [comment]
"Wallet listener started" "ngrok service started" "tor started "listener started" but no "Node started".

**Comment by gbkelley** [comment]
I had this problem on first install. Going into setup and re-selecting 'Built-in' instead of leaving the default value in assistant fixed it.

**Comment by Leviyf** [comment]
That node did not either work and switching back did not sync the internal node. But it is wierd because this node https://fastepic.eu:3413 works. Now that I have put in this node and it sync, then I go back to internal node and it works! The internal node seems to need a external node to sync before syncing itself.

**Comment by johanneshahn** [comment]
can not reproduce.
