### ISSUE TITLE
GUI is blank

### ISSUE THREAD

**Issue by inwtx** [EpicCash/epic-gui-wallet#71]
**Describe the bug**
GUI is blank, nothing on it.

**To Reproduce**
Start it.

**Expected behavior**
Expected titles, boxes, buttons, etc

**Required data**
 EpicWallet.Setup.4.0.6-beta.exe 

**Additional context**
My OS: Dell Windows 7
Installation good. Upon start, there are 4 occurrences show up in Process Manager.
Picture: https://i.imgur.com/LETuUny.png

**Comment by johanneshahn** [comment]
Windows 7 is not supported. Please upgrade Windows to 10 or 11
