### ISSUE TITLE
Blank black screen on GUI start up

### ISSUE THREAD

**Issue by zekexz** [EpicCash/epic-gui-wallet#9]
![image](https://user-images.githubusercontent.com/20370885/160301978-5a65b948-4b8b-4ea4-bc0a-5b15e47d5e29.png)
Black screen on start up if directory,  .epic ,  is missing from c/users/[username]  on windows

**Comment by johanneshahn** [comment]
#11 [fix bug where wallet can not start if ~/.epic folder is missing]
